/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fpliu_newton_MyApp */

#ifndef _Included_com_fpliu_newton_MyApp
#define _Included_com_fpliu_newton_MyApp
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    a
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_a
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    b
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_b
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_c
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    d
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_d
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    e
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_e
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    f
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_f
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    g
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_g
  (JNIEnv *, jobject);

/*
 * Class:     com_fpliu_newton_MyApp
 * Method:    h
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_fpliu_newton_MyApp_h
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
